name: mobile_tugas3
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15 # pastikan versinya terbaru
  shared_preferences_web: ^2.0.0 # Tambahkan paket ini untuk web
  intl: ^0.18.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         style: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         style: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         style: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         style: 800
